# Generated by Django 4.2.1 on 2023-05-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_gen_student_gender_rename_lev_student_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='gen',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='level',
            new_name='stuClass',
        ),
    ]
